### ISSUE TITLE
shopify: command not found

### ISSUE THREAD

**Issue by cheestudio** [sstur/shopify-ftp#4]
Not sure if this is active any longer, but after installing, am unsure on how to initialize the server:

When I paste the command, I get this:

$ shopify ftp [--port 2121] [--host 127.0.0.1]
sh: shopify: command not found

Any help? On Windows7 64bit.

**Comment by cheestudio** [comment]
Fixed by running shopify.js directly

**Comment by sstur** [comment]
I've updated the Readme to be clearer about how to use this. Thanks!

**Comment by cheestudio** [comment]
Thanks so much for getting to this!

**Comment by mroncetwice** [comment]
Yea, thank you very very much. It works without a hitch now :)
