### ISSUE TITLE
Client connection error

### ISSUE THREAD

**Issue by cheestudio** [sstur/shopify-ftp#5]
I get the following error connecting on my Windows7 64bit:

FTP server listening on 127.0.0.1:2121
FTP connection from 127.0.0.1
Client connection error: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Client connection closed

Any ideas?

**Comment by sstur** [comment]
This appears to be the same error that others have been getting on Windows. Closing as duplicate of #2. I will update that issue with any fix I can find.

**Comment by sstur** [comment]
This has now been fixed in the latest version. Please let me know if you run into any other issues on Windows. Thanks!
