### ISSUE TITLE
I don't understand ##usage

### ISSUE THREAD

**Issue by sheldonsteere** [sstur/shopify-ftp#7]
I'm probably doing this wrong, but I've spent the last hour and a half trying to figure out how to do it and there are no guides anywhere online.  So from how I understand your readme, I need to open terminal, type in 

npm install shopify-ftp

Once i type that in, I get:

shopify-ftp@0.1.8 node_modules/shopify-ftp
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── ftpd@0.2.11 (dateformat@1.0.7-1.2.3)
└── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.1, oauth-sign@0.8.0, caseless@0.11.0, stringstream@0.0.4, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.0, node-uuid@1.4.3, qs@5.2.0, combined-stream@1.0.5, mime-types@2.1.7, form-data@1.0.0-rc3, http-signature@0.11.0, hawk@3.1.0, bl@1.0.0, har-validator@2.0.2)

after that it says I'm supposed to type

shopify ftp [--port 2121] [--host 127.0.0.1]

then I get: -bash: shopify: command not found

(I also tried shopify ftp 2121 127.0.0.1  /  shopify ftp [2121] [127.0.0.1] / npm shopify ftp [--port 2121] [--host 127.0.0.1] / npm use shopify)

Nothing seems to work, and FileZilla returns:

Error:         	Could not connect to server
Status:       	Waiting to retry...
Status:       	Connecting to 127.0.0.1:2121...
Status:       	Connection attempt failed with "ECONNREFUSED - Connection refused by server".

I have no idea what I need to do with ##usage

I tried looking for the file node installs and opened node_modules/shopify-ftp/shopify.js

PLEASE tell me what I'm doing wrong!

**Comment by sstur** [comment]
Sorry the instructions are not more clear. First of all, you need to install "globally" to run the command you entered. You can install globally by adding the -g flag to your npm install command. Like this:

    npm install -g shopify

Secondly, when using command line interface you should not type the `[` and `]`. They signify that the `--port 2121` and `--host 127.0.0.1` options are not required. Meaning you can leave those out like:

    shopify ftp

Yet, if you want any values other than port 2121 or host 127.0.0.1 then you should add the options (but without the `[]`) In your cace you should not need to change the port or host.

I hope this helps.

**Comment by sheldonsteere** [comment]
that was awesome!  Thanks for the reply!

However I am still having trouble.

iMac-58B035EEB754-4:~ GraphicsDepartment$ npm install -g shopify
shopify@0.1.0 /usr/local/lib/node_modules/shopify
iMac-58B035EEB754-4:~ GraphicsDepartment$ shopify ftp
-bash: shopify: command not found

so then I tried 

iMac-58B035EEB754-4:~ GraphicsDepartment$ /usr/local/lib/node_modules/shopify-ftp/shopify.js ftp
-bash: /usr/local/lib/node_modules/shopify-ftp/shopify.js: No such file or directory

iMac-58B035EEB754-4:~ GraphicsDepartment$ open /usr/local/lib/node_modules/
![screen shot 2015-10-13 at 9 59 31 am](https://cloud.githubusercontent.com/assets/15093562/10462021/20e8a558-7191-11e5-945a-f85278608c74.png)

I discovered the directory is called "shopify" and not "shopify-ftp" but also that there is no shopify.js in that directory.

there is, however, a shopify.js in my local directory,
so I tried that

iMac-58B035EEB754-4:~ GraphicsDepartment$ /Users/GraphicsDepartment/node_modules/shopify-ftp/shopify.js
FTP server listening on 127.0.0.1:2121

I was excited!  I thought it worked, so then I plugged all the info into FileZilla and got back this:

Status:       	Connecting to 127.0.0.1:2121...
Status:       	Connection established, waiting for welcome message...
Status:       	Initializing TLS...
Error:         	GnuTLS error -15: An unexpected TLS packet was received.
Error:         	Could not connect to server
Status:       	Waiting to retry...
Status:       	Connecting to 127.0.0.1:2121...
Status:       	Connection established, waiting for welcome message...
Response: 	220 FTP server (nodeftpd) ready
Command: 	AUTH TLS
Response: 	202 Not supported
Status:       	Initializing TLS...
Error:         	GnuTLS error -15: An unexpected TLS packet was received.
Error:         	Could not connect to server

**Comment by sheldonsteere** [comment]
Ok I tried checking for firewalls on my end, but everything was off, so I tried Fetch instead of FileZilla, because I thought it might be better.  Looks like I got in with the credentials, but now I am seeing this as the file subsystem:

![screen shot 2015-10-13 at 10 21 01 am](https://cloud.githubusercontent.com/assets/15093562/10462523/217b2236-7194-11e5-8c90-537fb98373ca.png)

this doesn't seem to be truly ftp-ing into my page?

**Comment by sstur** [comment]
Oops, the `shopify` package on npm is not ours. It's someone else's. This package is called `shopify-ftp` so that explains why you see `-bash: shopify: command not found` and why shopify.js doesn't exist in the `/usr/local/lib/...`

Secondly, if you install with `-g` then you DO NOT need to specify the full path. If you install without `-g` then you need the full path, like you figured out (`/Users/.../node_modules/shopfiy-ftp/shopify.js`).

Next, Filezilla is trying to use SSL/TLS by the looks of it (`Status: Initializing TLS`). That is not supported. So you will need to turn this off in Filezilla, or else use a different FTP client, like you figured out.

Lastly, the file listing you see is a list of themes. You will need to figure out which theme you are using and go inside that folder then you should see your Shopify files.

**Comment by sheldonsteere** [comment]
Great!  I found my files!

But it doesn't appear I can make changes to the file system?

Tried to put in a file and it returned:

Fetch could not create the folder "NEWSLETTER" because the FTP server sent an unexpected response.
Check the Fetch Transcript window for more information.  Server responded: ""/Responsive/assets/NEWSLETTER" directory NOT created"

I checked the transcript window 

CWD NEWSLETTER
550 Directory not found.
MKD NEWSLETTER
550 "/Responsive/assets/NEWSLETTER" directory NOT created
Fetch could not create the folder “NEWSLETTER” because the FTP server sent an unexpected response. (Check the Fetch Transcript window for more information.
Server responded: “"/Responsive/assets/NEWSLETTER" directory NOT created”)
ftp_mkdir: 2,-30000 (state == RPUT_MAKING_DIR)
PWD

**Comment by sstur** [comment]
As far as I know, Shopify is very restrictive about the file system. I don't think you can create arbitrary folders, you must use their folder structure and simply add/remove files. This is not a limitation of the FTP module, but related to Shopify server.

**Comment by sstur** [comment]
I have fixed the issue with FileZilla and I have also updated the Readme with clearer instructions. Please let me know if this helps!
